//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KollegeKon.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string LogInTime { get; set; }
        public string LogOutTime { get; set; }
        public string TimeSpent { get; set; }
        public string UnsuccesfulLogOut { get; set; }
        public int IdAccount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
