//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KollegeKon.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        public int IdCouple { get; set; }
        public int IdGroup { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Couple Couple { get; set; }
        public virtual Group Group { get; set; }
    }
}
